### ISSUE TITLE
Inconsistent date pill color in Android

### ISSUE THREAD

**Issue by mangkoran** [catppuccin/telegram#13]
First of all, thank you for maintainers for all of your works!

I noticed that the date flyout (not sure its the correct name) color in Android could be improved. Currently it is hard to see if you have dark background.

Below is image using Mocha. The "November 30" and "December 1" are barely seen.
![Screenshot_20221205-003105_org telegram messenger ForkApplicationLoader](https://user-images.githubusercontent.com/57625126/205506054-157a43da-7552-420a-b81d-2749c6d732ca.png)

Compared to Desktop version which has light container and dark text.
![image](https://user-images.githubusercontent.com/57625126/205837667-81f293a8-e096-459d-8d5e-bb95b1e930b9.png)

Maybe it could be improved by using light text/dark container or dark text/light container.

**Comment by mangkoran** [comment]
If you could point out which line that should be updated, I will gladly try the combination and open a PR 😁

**Comment by Readpato** [comment]
I think it's this [line](https://github.com/catppuccin/telegram/blob/5ce8614aab1a6f9bfc6aa3dcebb6abbcc53b9b51/src/mocha/android#L349) might be this one, but maybe we can get a confirmation? I am up to create PR as well if needed

**Comment by mangkoran** [comment]
Thank you for your suggestion! It could be the right variable. However, I am not really sure what should we update it to, as if I compare it to the desktop version, the color is not existed in the Catppuccin colors or any variable in this repo.

![image](https://user-images.githubusercontent.com/57625126/216761216-a204d0ee-8757-447e-9a05-56fe2104946a.png)

Maybe we could update it to `text` or `blue` and call it a day?

We need your suggestion @NamesCode @andreasgrafen

**Comment by NamesCode** [comment]
Sky would probably be the best replacement for it

**Comment by mangkoran** [comment]
May I know how to update the theme for mobile?

**Comment by mangkoran** [comment]
Tried to update the element (`chat_serviceBackground`, which is currently missing in the repo). Below is the result.

sky `#89dceb`
![Screenshot_20230427-092045_Fork Client](https://user-images.githubusercontent.com/57625126/234745746-49c1d886-4ddf-4da6-8724-0061a7dc4fcb.png)

lavender `#b4befe`
![Screenshot_20230427-092422_Fork Client](https://user-images.githubusercontent.com/57625126/234745790-169baf35-268f-434c-8933-e0e2692c788a.png)

text `#cdd6f4`
![Screenshot_20230427-092528_Fork Client](https://user-images.githubusercontent.com/57625126/234745799-e99e0ca1-c554-4072-884b-75869cc2fc41.png)

IMO text is more suited for the theme. I will create PR for this.
