### ISSUE TITLE
Too bright default users avatars text. 

### ISSUE THREAD

**Issue by BANanaD3V** [catppuccin/telegram#3]
![Screenshot_20221009-220129165 (1)](https://user-images.githubusercontent.com/68944906/194774873-ae9961f3-543b-4c8b-bc9c-05ee7a0842d4.png)

**Comment by isabelincorp** [comment]
Which version is this on?

**Comment by ghostx31** [comment]
Fixed with https://github.com/catppuccin/telegram/commit/5ce8614aab1a6f9bfc6aa3dcebb6abbcc53b9b51
