### ISSUE TITLE
Update to Catppuccin 0.2.0

### ISSUE THREAD

**Issue by jasoncrevier** [catppuccin/telegram#5]
I use Frappe on the rest of my system, so I'd love a variant of this theme to match.

Don't have a ton of time to work on it, but I will get started, if no one else is already working on this. Opening this issue to track progress.

---
Edit by Catppuccin staff:
Tracking the Progress for each platform here:
- [x] iOS
- [x] Android
- [x] Desktop
- [x] macOS

**Comment by nekowinston** [comment]
Hi there :wave:

Thanks for the issue, it's actually [the last port](https://github.com/orgs/catppuccin/projects/2) that needs to be converted to the 0.2.0 spec.
We're currently also tracking the update in [our Discord](https://discord.gg/r6Mdz5dpFc), but progress has been slow.

I'd appreciate any help the maintainers can get.

**Comment by isabelincorp** [comment]
Currently, the android version is entirely done, but you can look at the progress [here on the dev branch](https://github.com/catppuccin/telegram/blob/dev/README.md)

**Comment by jasoncrevier** [comment]
Thank you both! I'm most eager for desktop, so I'll get started there. The completed android should be a good reference.

**Comment by isabelincorp** [comment]
iOS is now completed.

**Comment by isabelincorp** [comment]
Desktop is nearly completion (as you can see from the new screenshots).

**Comment by isabelincorp** [comment]
Telegram is now ported entirely.

**Comment by nekowinston** [comment]
and we're back: https://istelegramportedyet.lol/

**Comment by isabelincorp** [comment]
> well, merge dev to master then?

Done! #12
